version: '2.0'

networks:
  conpot_kamstrup_local:

services:

# Conpot service using Kamstrup Template
  conpot_kamstrup:
    container_name: conpot_kamstrup
    restart: always
    networks:
     - conpot_kamstrup_local
    ports:
     - "1025:1025"
     - "50100:50100"
#   image: "dtagdevsec/conpot:1710"
    image: "uncleraymondo/conpot_kamstrup:1710"
    volumes:
     - /data/conpot/log:/var/log/conpot