version: '2.0'

networks:
  conpot_default_local:

services:

# Conpot service using Default Siemens S7-200 Template
  conpot_default:
    container_name: conpot_default
    restart: always
    networks:
     - conpot_default_local
    ports:
     - "102:102"
     - "502:502"
     - "623:623/udp"
     - "47808:47808/udp"
     - "161:161/udp"
#   image: "dtagdevsec/conpot:1710"
    image: "uncleraymondo/conpot_default:1710"
    volumes:
     - /data/conpot/log:/var/log/conpot